### ISSUE TITLE
TypeError: Cannot read property 'motor' of undefined

### ISSUE THREAD

**Issue by Evoliofly** [hybridgroup/cylon#267]
Hello, I encountered an issue while trying to run a demo from the doc.
I try to start and stop a motor on an arduino with firmata from a Raspberry Pi. 
First of all, uname:
Linux raspberrypi 3.12.35+ #730 PREEMPT Fri Dec 19 18:31:24 GMT 2014 armv6l GNU/Linux
and node v0.10.36

Here's what I'm running:

```
var Cylon = require('cylon');

Cylon.robot({
  connections: {
    arduino: { adaptor: 'firmata', port: '/dev/ttyACM0' }
  },

  devices: {
    motor: { driver: 'motor', pin: 3 }
  },

  work: function(my) {
    my.motor.speed(100);

    after((1).seconds(), function(my) {
      my.motor.stop();
    });
  }
}).start();
```

```
pi@raspberrypi ~ $ node ppe3.js
I, [2015-02-19T01:03:42.253Z]  INFO -- : Initializing connections.
I, [2015-02-19T01:03:44.363Z]  INFO -- : Initializing devices.
I, [2015-02-19T01:03:44.493Z]  INFO -- : Starting connections.
I, [2015-02-19T01:03:47.734Z]  INFO -- : Starting devices.
I, [2015-02-19T01:03:47.743Z]  INFO -- : Working.

/home/pi/ppe3.js:16
      my.motor.stop();
        ^
TypeError: Cannot read property 'motor' of undefined
    at null._onTimeout (/home/pi/ppe3.js:16:9)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

```

Also...

```
pi@raspberrypi ~ $ npm ls
/home/pi
├─┬ cylon@0.22.0
│ └── async@0.9.0
├─┬ cylon-firmata@0.19.0
│ ├─┬ cylon@0.22.0
│ │ └── async@0.9.0
│ ├── cylon-gpio@0.22.0
│ ├── cylon-i2c@0.19.0
│ └─┬ firmata@0.4.0
│   ├── browser-serialport@2.0.1
│   ├── object-assign@1.0.0
│   └─┬ serialport@1.4.10
│     ├── async@0.9.0
│     ├── bindings@1.2.1
│     ├── nan@1.3.0
│     ├─┬ node-pre-gyp@0.5.19
│     │ ├─┬ mkdirp@0.5.0
│     │ │ └── minimist@0.0.8
│     │ ├─┬ nopt@2.2.1
│     │ │ └── abbrev@1.0.5
│     │ ├─┬ npmlog@0.0.6
│     │ │ └── ansi@0.2.1
│     │ ├─┬ rc@0.4.0
│     │ │ ├── deep-extend@0.2.10
│     │ │ ├── ini@1.1.0
│     │ │ ├── minimist@0.0.10
│     │ │ └── strip-json-comments@0.1.3
│     │ ├─┬ request@2.36.0
│     │ │ ├── aws-sign2@0.5.0
│     │ │ ├── forever-agent@0.5.2
│     │ │ ├─┬ form-data@0.1.2
│     │ │ │ ├── async@0.2.10
│     │ │ │ └─┬ combined-stream@0.0.4
│     │ │ │   └── delayed-stream@0.0.5
│     │ │ ├─┬ hawk@1.0.0
│     │ │ │ ├── boom@0.4.2
│     │ │ │ ├── cryptiles@0.2.2
│     │ │ │ ├── hoek@0.9.1
│     │ │ │ └── sntp@0.2.4
│     │ │ ├─┬ http-signature@0.10.0
│     │ │ │ ├── asn1@0.1.11
│     │ │ │ ├── assert-plus@0.1.2
│     │ │ │ └── ctype@0.5.2
│     │ │ ├── json-stringify-safe@5.0.0
│     │ │ ├── mime@1.2.11
│     │ │ ├── node-uuid@1.4.1
│     │ │ ├── oauth-sign@0.3.0
│     │ │ ├── qs@0.6.6
│     │ │ ├─┬ tough-cookie@0.12.1
│     │ │ │ └── punycode@1.2.4
│     │ │ └── tunnel-agent@0.4.0
│     │ ├── rimraf@2.2.8
│     │ ├── semver@2.3.0
│     │ ├─┬ tar@0.1.19
│     │ │ ├── block-stream@0.0.7
│     │ │ ├─┬ fstream@0.1.25
│     │ │ │ ├── graceful-fs@2.0.3
│     │ │ │ └── mkdirp@0.3.5
│     │ │ └── inherits@2.0.1
│     │ └─┬ tar-pack@2.0.0
│     │   ├── debug@0.7.4
│     │   ├─┬ fstream@0.1.25
│     │   │ ├── graceful-fs@2.0.3
│     │   │ ├── inherits@2.0.1
│     │   │ └── mkdirp@0.3.5
│     │   ├─┬ fstream-ignore@0.0.7
│     │   │ ├── inherits@2.0.1
│     │   │ └─┬ minimatch@0.2.14
│     │   │   ├── lru-cache@2.5.0
│     │   │   └── sigmund@1.0.0
│     │   ├── graceful-fs@1.2.3
│     │   ├── once@1.1.1
│     │   ├─┬ readable-stream@1.0.27-1
│     │   │ ├── core-util-is@1.0.1
│     │   │ ├── inherits@2.0.1
│     │   │ ├── isarray@0.0.1
│     │   │ └── string_decoder@0.10.25-1
│     │   └── uid-number@0.0.3
│     ├─┬ optimist@0.6.1
│     │ ├── minimist@0.0.10
│     │ └── wordwrap@0.0.2
│     └── sf@0.1.7
├── cylon-gpio@0.22.0
├── cylon-i2c@0.19.0
├─┬ cylon-opencv@0.12.0
│ └─┬ opencv@1.0.0 (git://github.com/hybridgroup/node-opencv.git#3558be3d50f03e80b002b519762f09b18ea790a3)
│   ├── buffers@0.1.1
│   ├── nan@1.4.3
│   └─┬ node-pre-gyp@0.5.31
│     ├─┬ mkdirp@0.5.0
│     │ └── minimist@0.0.8
│     ├─┬ nopt@3.0.1
│     │ └── abbrev@1.0.5
│     ├─┬ npmlog@0.1.1
│     │ └── ansi@0.3.0
│     ├─┬ rc@0.5.2
│     │ ├── deep-extend@0.2.11
│     │ ├── ini@1.1.0
│     │ ├── minimist@0.0.10
│     │ └── strip-json-comments@0.1.3
│     ├─┬ request@2.47.0
│     │ ├── aws-sign2@0.5.0
│     │ ├─┬ bl@0.9.3
│     │ │ └─┬ readable-stream@1.0.33
│     │ │   ├── core-util-is@1.0.1
│     │ │   ├── inherits@2.0.1
│     │ │   ├── isarray@0.0.1
│     │ │   └── string_decoder@0.10.31
│     │ ├── caseless@0.6.0
│     │ ├─┬ combined-stream@0.0.5
│     │ │ └── delayed-stream@0.0.5
│     │ ├── forever-agent@0.5.2
│     │ ├─┬ form-data@0.1.4
│     │ │ ├── async@0.9.0
│     │ │ └── mime@1.2.11
│     │ ├─┬ hawk@1.1.1
│     │ │ ├── boom@0.4.2
│     │ │ ├── cryptiles@0.2.2
│     │ │ ├── hoek@0.9.1
│     │ │ └── sntp@0.2.4
│     │ ├─┬ http-signature@0.10.0
│     │ │ ├── asn1@0.1.11
│     │ │ ├── assert-plus@0.1.2
│     │ │ └── ctype@0.5.2
│     │ ├── json-stringify-safe@5.0.0
│     │ ├── mime-types@1.0.2
│     │ ├── node-uuid@1.4.1
│     │ ├── oauth-sign@0.4.0
│     │ ├── qs@2.3.1
│     │ ├── stringstream@0.0.4
│     │ ├─┬ tough-cookie@0.12.1
│     │ │ └── punycode@1.3.2
│     │ └── tunnel-agent@0.4.0
│     ├── rimraf@2.2.8
│     ├── semver@4.1.0
│     ├─┬ tar@1.0.1
│     │ ├── block-stream@0.0.7
│     │ ├─┬ fstream@1.0.2
│     │ │ └── graceful-fs@3.0.4
│     │ └── inherits@2.0.1
│     └─┬ tar-pack@2.0.0
│       ├── debug@0.7.4
│       ├─┬ fstream@0.1.31
│       │ ├── graceful-fs@3.0.4
│       │ └── inherits@2.0.1
│       ├─┬ fstream-ignore@0.0.7
│       │ ├── inherits@2.0.1
│       │ └─┬ minimatch@0.2.14
│       │   ├── lru-cache@2.5.0
│       │   └── sigmund@1.0.0
│       ├── graceful-fs@1.2.3
│       ├── once@1.1.1
│       ├─┬ readable-stream@1.0.33
│       │ ├── core-util-is@1.0.1
│       │ ├── inherits@2.0.1
│       │ ├── isarray@0.0.1
│       │ └── string_decoder@0.10.31
│       ├─┬ tar@0.1.20
│       │ ├── block-stream@0.0.7
│       │ └── inherits@2.0.1
│       └── uid-number@0.0.3
├── cylon-speech@0.6.0
└─┬ npmbox@2.1.1
  ├── is@2.2.0
  ├─┬ npm@2.4.1
  │ ├── abbrev@1.0.5
  │ ├── ansi@0.3.0
  │ ├── ansicolors@0.3.2
  │ ├── ansistyles@0.1.3
  │ ├── archy@1.0.0
  │ ├── async-some@1.0.1
  │ ├── block-stream@0.0.7
  │ ├── char-spinner@1.0.1
  │ ├── child-process-close@0.1.1
  │ ├── chmodr@0.1.0
  │ ├── chownr@0.0.1
  │ ├── cmd-shim@2.0.1
  │ ├─┬ columnify@1.3.2
  │ │ ├─┬ strip-ansi@2.0.0
  │ │ │ └── ansi-regex@1.1.0
  │ │ └─┬ wcwidth@1.0.0
  │ │   └─┬ defaults@1.0.0
  │ │     └── clone@0.1.19
  │ ├─┬ config-chain@1.1.8
  │ │ └── proto-list@1.2.3
  │ ├─┬ dezalgo@1.0.1
  │ │ └── asap@1.0.0
  │ ├── editor@0.1.0
  │ ├── fs-vacuum@1.2.5
  │ ├── fs-write-stream-atomic@1.0.2
  │ ├── fstream@1.0.3
  │ ├─┬ fstream-npm@1.0.1
  │ │ └── fstream-ignore@1.0.2
  │ ├── github-url-from-git@1.4.0
  │ ├── github-url-from-username-repo@1.0.2
  │ ├── glob@4.3.5
  │ ├── graceful-fs@3.0.5
  │ ├── inflight@1.0.4
  │ ├── inherits@2.0.1
  │ ├── ini@1.3.2
  │ ├─┬ init-package-json@1.2.0
  │ │ └── promzard@0.2.2
  │ ├── lockfile@1.0.0
  │ ├── lru-cache@2.5.0
  │ ├─┬ minimatch@2.0.1
  │ │ └─┬ brace-expansion@1.0.1
  │ │   ├── balanced-match@0.2.0
  │ │   └── concat-map@0.0.0
  │ ├─┬ mkdirp@0.5.0
  │ │ └── minimist@0.0.8
  │ ├─┬ node-gyp@1.0.2
  │ │ └─┬ minimatch@1.0.0
  │ │   └── sigmund@1.0.0
  │ ├── nopt@3.0.1
  │ ├── normalize-git-url@1.0.0
  │ ├── normalize-package-data@1.0.3
  │ ├── npm-cache-filename@1.0.1
  │ ├── npm-install-checks@1.0.5
  │ ├── npm-package-arg@2.1.3
  │ ├─┬ npm-registry-client@6.0.3
  │ │ ├─┬ concat-stream@1.4.7
  │ │ │ ├─┬ readable-stream@1.1.13
  │ │ │ │ ├── core-util-is@1.0.1
  │ │ │ │ ├── isarray@0.0.1
  │ │ │ │ └── string_decoder@0.10.31
  │ │ │ └── typedarray@0.0.6
  │ │ └─┬ npm-package-arg@3.0.0
  │ │   └── hosted-git-info@1.5.3
  │ ├── npm-user-validate@0.1.1
  │ ├── npmlog@0.1.1
  │ ├── once@1.3.1
  │ ├── opener@1.4.0
  │ ├── osenv@0.1.0
  │ ├── path-is-inside@1.0.1
  │ ├─┬ read@1.0.5
  │ │ └── mute-stream@0.0.4
  │ ├─┬ read-installed@3.1.5
  │ │ ├── debuglog@1.0.1
  │ │ ├── readdir-scoped-modules@1.0.1
  │ │ └── util-extend@1.0.1
  │ ├── read-package-json@1.2.7
  │ ├─┬ readable-stream@1.0.33
  │ │ ├── core-util-is@1.0.1
  │ │ ├── isarray@0.0.1
  │ │ └── string_decoder@0.10.31
  │ ├── realize-package-specifier@1.3.0
  │ ├─┬ request@2.51.0
  │ │ ├── aws-sign2@0.5.0
  │ │ ├── bl@0.9.3
  │ │ ├── caseless@0.8.0
  │ │ ├─┬ combined-stream@0.0.7
  │ │ │ └── delayed-stream@0.0.5
  │ │ ├── forever-agent@0.5.2
  │ │ ├─┬ form-data@0.2.0
  │ │ │ ├── async@0.9.0
  │ │ │ └─┬ mime-types@2.0.4
  │ │ │   └── mime-db@1.3.0
  │ │ ├─┬ hawk@1.1.1
  │ │ │ ├── boom@0.4.2
  │ │ │ ├── cryptiles@0.2.2
  │ │ │ ├── hoek@0.9.1
  │ │ │ └── sntp@0.2.4
  │ │ ├─┬ http-signature@0.10.0
  │ │ │ ├── asn1@0.1.11
  │ │ │ ├── assert-plus@0.1.2
  │ │ │ └── ctype@0.5.2
  │ │ ├── json-stringify-safe@5.0.0
  │ │ ├── mime-types@1.0.2
  │ │ ├── node-uuid@1.4.2
  │ │ ├── oauth-sign@0.5.0
  │ │ ├── qs@2.3.3
  │ │ ├── stringstream@0.0.4
  │ │ ├─┬ tough-cookie@0.12.1
  │ │ │ └── punycode@1.3.2
  │ │ └── tunnel-agent@0.4.0
  │ ├── retry@0.6.1
  │ ├── rimraf@2.2.8
  │ ├── semver@4.2.0
  │ ├─┬ sha@1.3.0
  │ │ └─┬ readable-stream@1.1.13
  │ │   ├── core-util-is@1.0.1
  │ │   ├── isarray@0.0.1
  │ │   └── string_decoder@0.10.31
  │ ├── slide@1.1.6
  │ ├── sorted-object@1.0.0
  │ ├── tar@1.0.3
  │ ├── text-table@0.2.0
  │ ├── uid-number@0.0.6
  │ ├── umask@1.1.0
  │ ├── which@1.0.8
  │ ├── wrappy@1.0.1
  │ └── write-file-atomic@1.1.0
  ├─┬ optimist@0.6.1
  │ ├── minimist@0.0.10
  │ └── wordwrap@0.0.2
  ├── rimraf@2.2.8
  └─┬ tar.gz@0.1.1
    ├─┬ commander@1.1.1
    │ └── keypress@0.1.0
    ├─┬ fstream@0.1.31
    │ ├── graceful-fs@3.0.5
    │ ├── inherits@2.0.1
    │ └─┬ mkdirp@0.5.0
    │   └── minimist@0.0.8
    └─┬ tar@0.1.20
      ├── block-stream@0.0.7
      └── inherits@2.0.1
```

So, the motor is working but I don't manage to stop it...

Thank you. :)

**Comment by stewart** [comment]
Hi @Evoliofly - in your code you're passing introducing another `my` scope here:

```javascript
    after((1).seconds(), function(my) { // <- here
      my.motor.stop();
    });
```

If you get rid of that extra `my`, your code should work.

**Comment by Evoliofly** [comment]
Thank you.
( http://cylonjs.com/documentation/drivers/motor/ )
