### ISSUE TITLE
error installing cylon-pebble@0.17.0

### ISSUE THREAD

**Issue by richacker** [hybridgroup/cylon#306]
root@raspberrypi:/home/pi/Desktop/rishi# npm install cylon cylon-pebble
npm WARN cylon@0.12.0 package.json: bugs['name'] should probably be bugs['url']
npm http GET http://registry.npmjs.org/cylon-pebble
npm http GET http://registry.npmjs.org/cylon
npm http 304 http://registry.npmjs.org/cylon-pebble
npm http 304 http://registry.npmjs.org/cylon
npm http GET http://registry.npmjs.org/cylon
npm http 304 http://registry.npmjs.org/cylon
npm ERR! error installing cylon-pebble@0.17.0

npm ERR! Error: No compatible version found: cylon@'>=1.1.0- <1.2.0-'
npm ERR! Valid install targets:
npm ERR! ["0.0.0","0.1.0","0.2.0","0.3.0","0.4.0","0.5.0","0.6.0","0.6.1","0.7.0","0.8.0","0.9.0","0.9.2","0.10.0","0.10.1","0.10.2","0.10.3","0.10.4","0.11.0","0.11.1","0.11.2","0.12.0"]
npm ERR! at installTargetsError (/usr/share/npm/lib/cache.js:488:10)
npm ERR! at next_ (/usr/share/npm/lib/cache.js:438:17)
npm ERR! at next (/usr/share/npm/lib/cache.js:415:44)
npm ERR! at /usr/share/npm/lib/cache.js:408:5
npm ERR! at saved (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR! at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR! 
npm ERR! or use
npm ERR! reportbug --attach /home/pi/Desktop/rishi/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.18.11-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "cylon" "cylon-pebble"
npm ERR! cwd /home/pi/Desktop/rishi
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message No compatible version found: cylon@'>=1.1.0- <1.2.0-'
npm ERR! message Valid install targets:
npm ERR! message ["0.0.0","0.1.0","0.2.0","0.3.0","0.4.0","0.5.0","0.6.0","0.6.1","0.7.0","0.8.0","0.9.0","0.9.2","0.10.0","0.10.1","0.10.2","0.10.3","0.10.4","0.11.0","0.11.1","0.11.2","0.12.0"]
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR! /home/pi/Desktop/rishi/npm-debug.log
npm not ok

**Comment by richacker** [comment]
resolved by npm install cylon@1.1.0 cylon-pebble
